services:
  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis.conf"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - redis-net

networks:
  redis-net:
